name: happeteer
version: '0.1.0.0'
category: Web
author: Author name here
maintainer: example@example.com
copyright: 2018 Author name here
license: BSD3
github: githubuser/happeteer
extra-source-files:
- README.md
dependencies:
- url >= 2.1.3
- JuicyPixels >= 3.2.9.5
- aeson >= 1.2.4.0
library:
  source-dirs: src
  ghc-options:
  - -Weverything
  - -Wno-unsafe
  - -Wno-implicit-prelude
  - -Wno-safe
  - -Werror
  exposed-modules:
  - Happeteer
  dependencies:
  - base >= 4.10.1.0
  - process >= 1.6.1.0
  - containers >= 0.5.10.2
  - text >= 1.2.3.0
  - bytestring >= 0.10.8.2
  - base64-bytestring >= 1.0.0.1
  - neat-interpolation >= 0.3.2.1
tests:
  lib-test:
    main: HappeteerTest.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.10.1.0
    - tasty >= 1.0.1.1
    - tasty-hunit >= 0.10.0.1
    - unordered-containers >= 0.2.9.0
    - happeteer
